### ISSUE TITLE
Guide for using with Elixir/Phoenix

### ISSUE THREAD

**Issue by jamilabreu** [meppu/surreal#5]
Hi! Could you please share a quick guide on how to use this within an Elixir/Phoenix project? I'd love to try it and give feedback 💜

**Comment by meppu** [comment]
You can check it out surreal_config module to create a connection with registered name. Then you can use that name to interact with surrealdb.

Since im not currently on home, i cant really show you an example but it is pretty much same with elixir. Just add surreal_config:load/1 with configs to your supervisor with child spec.

https://hexdocs.pm/elixir/1.14.5/Supervisor.html

And check README and docs for more about configs.

https://github.com/meppu/surreal#connect-with-config

https://hexdocs.pm/surreal/surreal_config.html#t:config_value/0

Using an erlang library in elixir is pretty much same but you use atoms for calling erlang modules.

**Comment by meppu** [comment]
with version `v1.0.1` now it is way easier to use with Elixir/Phoenix:

> Mix.exs (`/mix.exs`)
- Add surreal to your project
- Add `:surreal` to `extra_applications`:
  ```diff
  - extra_applications: [:logger, :runtime_tools]
  + extra_applications: [:logger, :runtime_tools, :surreal]
  ```
  
> Application.ex (`/lib/<name>/application.ex`)
- Add child to supervisor with [configs](https://hexdocs.pm/surreal/surreal_config.html#t:config_value/0), for example:
  ```elixir
  children = [
      # ...
      # This is where we initialize surreal connection with name.
      {:surreal_config, [:link, name: Testing.Surreal, host: "localhost", port: 8080, use: {"test", "test"}, signin: {"root", "root"}]}
  ]
  
  # ...
  Supervisor.start_link(children, opts)
  ```
  
 Now you can use surreal from anywhere you want with given name:
 ```elixir
 :surreal.create(Testing.Surreal, "user:joe", %{name: "example"})
 ```

**Comment by meppu** [comment]
I am closing this due to the lack of response from the issue owner for the past 2 weeks.
